### PR TITLE
fix: warn if transparent background is set after opaque init

### LINKED ISSUE #10162: Bug: Transparent Background doesn't work
### Current Behavior

The background transparency is not set further if I initialize the application with an opaque background.

### Expected Behavior

The background transparency should be set further if I initialize the application with an opaque background.

### Steps to Reproduce

1. Open example here [https://pixijs.com/examples/basic/transparent-background](https://pixijs.com/examples/basic/transparent-background)
2. Remove backgroundAlpha from constructor options. 
const app = new PIXI.Application({ backgroundColor: 'green', resizeTo: window });
// ... some code
3. Set a new background (red + 0.5 alpha)
app.renderer.background.color = 'rgba(255, 0, 0, 0.5)'; // doesn't work

Note: If backgroundAlpha is set to 0 in constructor then step 3 is works.

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Ashish050488**
Fixes #10162

Browsers do not allow changing the canvas alpha setting after initialization. If an Application
is created with `backgroundAlpha: 1`, the canvas becomes opaque and cannot later be made transparent.

This PR adds a helpful developer warning if a transparent background color (e.g., `rgba(...)`) is
set **after** initialization with an opaque background.

This avoids confusion when transparency doesn’t work unexpectedly.

**Console warning example:**

- [x] Lint process passed (`npm run lint`)
- [x] Code builds successfully (`npm run build`)
- [x] Manual test verified (background + warning)
- [ ] No automated tests needed (warning only)

### CODE REVIEW

**Comment by Ashish050488** [comment]
check it and let me know if i did anything wrong it would helpful for my growth also do let me know if there is any changes needed i am happy to do that

File: src/rendering/renderers/shared/background/BackgroundSystem.ts [hunk 1]
```diff
@@ -111,6 +111,16 @@ export class BackgroundSystem implements System<BackgroundSystemOptions>
...
+        const incoming = new Color(value);
+
+        if (incoming.alpha < 1 && this._backgroundColor.alpha === 1)
+        {
+            console.warn(
+                '[PixiJS] ✨ Cannot set a transparent background on an opaque canvas. '
+            + 'To enable transparency, set backgroundAlpha < 1 when initializing your Application.'
+            );
+        }
+
```
Comment (bigtimebuddy) [inline src/rendering/renderers/shared/background/BackgroundSystem.ts]: Can you use `import { warn } from '../../../../utils/logging/warn';` here which provides some convenience with warnings? We also wrap our warnings in these comment to exclude from minified releases.

```suggestion
        // #if _DEBUG
        const incoming = new Color(value);

        if (incoming.alpha < 1 && this._backgroundColor.alpha === 1)
        {
           warn(
                'Cannot set a transparent background on an opaque canvas. '
            + 'To enable transparency, set backgroundAlpha < 1 when initializing your Application.'
            );
        }
        // #endif

```

**Review by bigtimebuddy — COMMENTED** [review]
Thank you for making this change :+1: Just a few comments about how we typically ship warnings like this. Also, would welcome a similar comment in the docs for `BackgroundSystemOptions.backgroundAlpha`.

**Comment by Ashish050488** [comment]
Updated as suggested now using warn() wrapped in #if _DEBUG

**Comment by bigtimebuddy** [comment]
Much better! Thank you. Would you mind adding a comments for the docs too?

**Comment by Ashish050488** [comment]
yeah sure

**Comment by Ashish050488** [comment]
Added the comments for the docs

**Comment by bigtimebuddy** [comment]
Oh sorry if I wasn't clear enough. I meant to add the additional context here:
https://github.com/Ashish050488/pixijs/blob/685794b9efaacf34f8a54087aa263cf4d79116c4/src/rendering/renderers/shared/background/BackgroundSystem.ts#L22

Which would show up here when we generate docs:
https://pixijs.download/dev/docs/rendering.BackgroundSystemOptions.html#backgroundalpha

**Comment by Ashish050488** [comment]
* Transparency of the background color, value from `0` (fully transparent) to `1` (fully opaque).
    * This value determines whether the canvas is initialized with alpha transparency support.
    * Note: This cannot be changed after initialization. If set to `1`, the canvas will remain opaque,
    * even if a transparent background color is set later. is this comment good let me know then i will push it
    *

**Comment by bigtimebuddy** [comment]
Yeah, looks great

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Oh, looks like you merged this into your fork's dev branch. Can you make a PR back to the main project?
